import React from 'react';
import { ContentOuterContainer, ContentInnerContainer }from '../styles.js';

const Description = (props) => (
  <ContentOuterContainer>
    <ContentInnerContainer>
        <h3>Description</h3>
        <p>WELCOME TO LUMAHAI VILLAS! MAGNIFICENT ESTATE WITH SWEEPING PANORAMIC OCEAN VIEWS. ONE OF A KIND LOCATION SITTING ATOP KOKO KAI NEIGHBORHOOD. INDOOR AND OUTDOOR LIVING AT ITS BEST! BEAUTIFULLY REMODELED FROM TOP TO BOTTOM INCLUDING NEW PUKA LAVA POOL DECK WITH CEDAR CEILING AND PILLARS ON YOUR POOL PATIO . ALL NEWLY RELEASED CHEF GE APPLIANCES, HARDWOOD AND LUXURY VINYL FLOORING, IMPORTED COUNTER TOPS, HIGH GLOSS ACRYLIC CABINETS. ADJUSTABLE HEATED FLOOR TILES IN YOUR MASTER BATHROOM. NEW BEAUTIFUL LANDSCAPING. CUSTOM MAHOGANY DOORS. HOME THEATER ROOM! GUEST HOUSE SITS ON THE VERY TOP OF THE PROPERTY WITH A PRIVATE GAZEBO THAT LOOKS OVER THE PACIFIC OCEAN. THIS PROPERTY SCREAMS EXCLUSIVE AND LUXURY! MUST SEE IT TO APPRECIATE ALL THE DETAILS. FIRST OPEN HOUSE NOVEMBER 10TH, 2-5PM. TO VIEW MATTERPORT 3D TOUR FOR MAIN HOUSE PLEASE GO TO http://my.matterport.com/show/?m=2iPgxUFYx54&mls=1 TO VIEW MATTERPORT 3D TOUR FOR GUEST HOUSE PLEASE GO TO http://my.matterport.com/show/?m=YNfzBDAFigE&mls=1</p>
    </ContentInnerContainer>
  </ContentOuterContainer>
);


export default Description;